name: workflow

on: [ push, workflow_dispatch ]

permissions:
  contents: write

jobs:
  list-mods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - uses: vspr-sh/packwiz-export-action@master
        id: packwiz-export
        with:
          autoupdate: https://packwiz.thisdomaindoesnotexist.com/pack.toml

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.packwiz-export.outputs.file-list }}
