name: list-mods

on: [ push, workflow_dispatch ]

permissions:
  contents: write

jobs:
  list-mods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - uses: vspr-sh/packwiz-export-action@master

      - name: List mods
        run: packwiz list
