name: list-mods

on: [ push, workflow_dispatch ]

jobs:
  list-mods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup packwiz CLI
        uses: vspr-sh/setup-packwiz-action@master

      - name: List mods
        run: packwiz list
